### PR TITLE
feat: move to lazy and fix many issues

### LINKED ISSUE #136: Syntax highlighting for TSX files
**Describe the bug**
The syntax highlighting for TSX isn't working properly. You can take a look at the color of the HTML tags and the content inside them, they are the same color. I'm using the same theme settings that are in the `init.lua` repo. However, I've also tried another theme, the Catppuccin, and I faced inconsistencies with the syntax highlighting as well.

image

**To Reproduce**
1. Follow the guide in the README
2. Open a TSX file

**Desktop (please complete the following information):**
- OS: macOS Ventura 13.1
- Terminal: Kitty 0.26.4

** Neovim Version **
 - Output of running `:version` from inside of neovim: NVIM v0.8.2 
 
 
File example

```
import React from "react";

type Props = { text: string; color?: string };

function Title({ text, color }: Props) {
  const style = { color: color ?? "blueviolet" };
  return <h1 style={style}>{text}</h1>;
}

const Header = () => <header>Header component</header>;

export const App = () => (
  <>
    <Header />
    <Title text="Hello World" />
    <p>
      lorem ipsum dolor etc lorem ipsum dolor etc lorem ipsum dolor etc lorem
      ipsum dolor etc lorem ipsum dolor etc lorem ipsum dolor etc
    </p>
  </>
);
```

### LINKED ISSUE #158: How to implement format on save
Can anyone give me some advice on how to implement format on save with prettier and eslint for typescript?

### LINKED ISSUE #160: without modifying `init.lua`, <leader> cannot be set in time for supplied keymaps
I want to try kickstart in its simple form, and be able to update it periodically.
That said, I have years of use with a different `<leader>`. Changing leader after init.lua loads doesn't help, as that means all the builtin keymaps use `<space>`, and my addon customs use another.

Proposal: inject a config call, immediately after leader (and other vim base settings) are set, giving the user a change to override those before the remaining keymaps and plugin setups run.

PR to come shortly.

### LINKED ISSUE #174: Sumneko_lua is not   recognized
**Describe the bug**

**To Reproduce**
1. ...

**Desktop (please complete the following information):**
- OS: archlinux
- Terminal: alacritty

** Neovim Version **
 - Output of running `:version 0.8.2` from inside of neovim:
```
[mason-lspconfig.nvim] Server "sumneko_lua" is not a valid entry in ensure_installed. Make sure to only pro
vide lspconfig server names.
```

### LINKED ISSUE #176: No plugins from custom.plugins is loaded
I have the same problem as described in #34.
I've commented in that issue quite a bit.
**To Reproduce**
1. Add plugins to `~/.config/nvim/lua/custom/plugins.lua`
2. Re-start vim or run `PackerSync`
3. No plugins from custom.plugins is installed

**Desktop (please complete the following information):**
- OS: macOS 13.2
- Terminal: iTerm2

** Neovim Version **
 - Output of running `:version` from inside of neovim:

```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"
```
My current `~/.config/nvim/lua/custom/plugins.lua`: https://github.com/jby/nvim/blob/nvks/lua/custom/plugins.lua
```lua
return function(use)
  -- Configure nvim-tree
  use({
    {'nvim-tree/nvim-tree.lua', requires = 'nvim-tree/nvim-web-devicons'},
    config = function()
      require("nvim-tree").setup()
      'nvim-tree/nvim-web-devicons'
    end
  })
  -- Add friendly snippets
  use({
    'rafamadriz/friendly-snippets',
    config = function ()
      require('luasnip.loader.from_vscode').lazy_load()
    end
  })
end
```

### PR DESCRIPTION
**Pull request by tjdevries**
Closes #175
Closes #177
Closes #173
Closes #169
Closes #161
Closes #144
Closes #138
Fixes #136
Closes #137
Closes #131
Closes #117
Closes #130
Closes #115
Closes #86
Closes #105
Closes #70
Fixes #176
Fixes #174
Fixes #160
Fixes #158

### CODE REVIEW

File: lua/kickstart/plugins/debug.lua [hunk 1]
```diff
@@ -0,0 +1,69 @@
+return {
+  {
+    enabled = true,
+    config = function()
+      -- Optional debug adapter setup
+      --
+      -- To enable setup, change `disable = true` in the packer section
```
Comment (feoh) [inline lua/kickstart/plugins/debug.lua:7]: Guessing you'll want to update 'in the packer section' to something lazy.nvim specific?

File: lua/kickstart/plugins/debug.lua [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+          },
+        },
+      }
+
+      dap.listeners.after.event_initialized['dapui_config'] = dapui.open
+      dap.listeners.before.event_terminated['dapui_config'] = dapui.close
+      dap.listeners.before.event_exited['dapui_config'] = dapui.close
+
+      -- Install golang specific config
+      require('dap-go').setup()
```
Comment (feoh) [inline lua/kickstart/plugins/debug.lua:66]: Pardon my ignorance, but will it be clear to folks where they should add the require().setup() for their own favorite languages?

File: lua/kickstart/plugins/debug.lua (hunk 1 above)
Comment (tjdevries) [reply lua/kickstart/plugins/debug.lua:7]: yeah, i will make it so the debug config works with lazy -- this was leftover from an old PR that I never submitted

File: lua/kickstart/plugins/debug.lua (hunk 2 above)
Comment (tjdevries) [reply lua/kickstart/plugins/debug.lua:66]: well you'll have to emulate what I've done here for golang -- i can list a few examples and the wiki entries to explore. I haven't done a bunch of DAP stuff for other languages

Comment (szechp) [reply lua/kickstart/plugins/debug.lua]: if you add:

Comment (szechp) [reply lua/kickstart/plugins/debug.lua]: here is my full call to nvim-dap with packer, for clarification:

```
	use { 'mfussenegger/nvim-dap',
		requires = {
			'theHamsta/nvim-dap-virtual-text', -- Show variable values in virtual text
			'jay-babu/mason-nvim-dap.nvim', -- Automatic DAP configuration
			'williamboman/mason.nvim',
		},
		config = function()
			vim.fn.sign_define('DapBreakpoint', { text = '', texthl = 'Error' })
			vim.fn.sign_define('DapBreakpointCondition', { text = 'לּ', texthl = 'Error' })
			vim.fn.sign_define('DapLogPoint', { text = '', texthl = 'Directory' })
			vim.fn.sign_define('DapStopped', { text = 'ﰲ', texthl = 'TSConstant' })
			vim.fn.sign_define('DapBreakpointRejected', { text = '', texthl = 'Error' })

			-- Automatically set up installed DAP adapters
			require('mason-nvim-dap').setup({ automatic_setup = true })
			require('mason-nvim-dap').setup_handlers()
			-- DAP virtual text --
			require('nvim-dap-virtual-text').setup()
		end
	}
```

Comment (tjdevries) [reply lua/kickstart/plugins/debug.lua]: Right, but some of the plugins give you additional configuration that allow you to do different types of debugging (like attaching to running process, run individual unit tests, etc)

Comment (feoh) [reply lua/kickstart/plugins/debug.lua]: This is something I've struggled with and hope to contribute back to help other newbies :)

Specifically, I find it tremendously confusing to understand how to express the configuration for any given plugin, and I think the root of the confusion is understaning what lua lexical/function closure/scope a given plugin wants for its configuration.

Take [this](https://github.com/feoh/git_dotfiles/blob/master/.config/nvim/lua/custom/plugins.lua#L1) for example - it took me forever to understand that wrapping all my extra 'use' directives in a `return function(use)` would allow Packer to ingest them despite their being in another file.

Is there a way to signpost this for new users? Will Lazy make this easier?

Thanks so much for all your hard work. kickstart.nvim & neovim have made me a more productive developer == PRICELESS :)

Comment (tjdevries) [reply lua/kickstart/plugins/debug.lua]: yes, the new method is much simpler and less error prone. I will add docs as well before I merge

File: .gitignore [hunk 3]
```diff
@@ -2,4 +2,4 @@ tags
 test.sh
 .luarc.json
 nvim
-plugin/packer_compiled.lua
+lazy-lock.json
```
Comment (zdcthomas) [inline .gitignore:5]: Hey! Thanks for the awesome setup, this is awesome for the community! 

I think the lazy-lock should probably be committed to maintain versions across multiple machines?

Comment (tjdevries) [reply .gitignore:5]: I don't think I want to commit mine. Users can commit their own though by modifying the gitignore.

Comment (zdcthomas) [reply .gitignore:5]: Sounds good!

**Comment by folke** [comment]
Hi! just had a quick look at that PR and the biggest thing you should pobably change is `config()` -> `opts`

So change:

```lua
{ -- Adds git releated signs to the gutter, as well as utilities for managing changes
    'lewis6991/gitsigns.nvim',
    config = function()
      -- See `:help gitsigns.txt`
      require('gitsigns').setup {
        signs = {
          add = { text = '+' },
          change = { text = '~' },
          delete = { text = '_' },
          topdelete = { text = '‾' },
          changedelete = { text = '~' },
        },
      }
    end,
  },
```

to 

```lua
{ -- Adds git releated signs to the gutter, as well as utilities for managing changes
    'lewis6991/gitsigns.nvim',
    opts = {
      signs = {
        add = { text = '+' },
        change = { text = '~' },
        delete = { text = '_' },
        topdelete = { text = '‾' },
        changedelete = { text = '~' },
      },
    }
}
```

File: .gitignore (hunk 3 above)
Comment (folke) [reply .gitignore:5]: @tjdevries I have the same problem for LazyVim. I don't add the lockfile to .gitignore and simply never add mine to the repo. This way for users, they won't forget to add the lockfile to git.

File: init.lua [hunk 4]
```diff
@@ -1,96 +1,187 @@
...
+--  You can configure plugins using the `config` key.
+--
+--  You can also configure plugins after the setup call,
+--    as they will be available in your neovim runtime.
+require('lazy').setup({
+  -- NOTE: First, some plugins that don't require any configuration
 
-  use { -- LSP Configuration & Plugins
+  -- Git related plugins
+  'tpope/vim-fugitive',
```
Comment (folke) [inline init.lua:53]: Just wanted to note here, that while this is totally fine to pass a plugins list to lazy, change detection won't work. Change detection only works when loading/importing plugins modules. So maybe something to mention as well.

File: README.md [hunk 5]
```diff
@@ -1,64 +1,87 @@
...
 
 ```lua
-use {'nvim-telescope/telescope-fzf-native.nvim', run = 'cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build' }
+-- File: lua/custom/plugins/autopairs.lua
+
+return {
+  "windwp/nvim-autopairs",
+  config = function()
+    require("nvim-autopairs").setup {}
+  end,
```
Comment (folke) [inline README.md:51]:
```lua
return {
  "windwp/nvim-autopairs",
  opts = {}
}

File: README.md [hunk 6]
```diff
@@ -1,64 +1,87 @@
...
-  use({
-    "folke/which-key.nvim",
-      config = function()
-        require("which-key").setup({})
-      end
-  })
-end
+return {
+  "nvim-neo-tree/neo-tree.nvim",
+  branch = "v2.x",
```
Comment (folke) [inline README.md:65]: lazy has full semver support, so better to use `version="2.*"` here, or just `version="*"` if you prefer to always install the latest stable release

File: README.md [hunk 7]
```diff
@@ -1,64 +1,87 @@
...
+  dependencies = {
+    "nvim-lua/plenary.nvim",
+    "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
+    "MunifTanjim/nui.nvim",
```
Comment (folke) [inline README.md:69]: Again, totally fine as is, but lua dependencies don't have to be explicitly defined with lazy.

With lazy, when a plugin loads, then first all its dependencies will be loaded. so in this case those three plugins would always be loaded, wether they are used or not.

If you don't specify the explicit dependencies, they would be automatically loaded when doing `require("plenary")` for example.

File: init.lua [hunk 8]
```diff
@@ -1,96 +1,187 @@
...
+    end,
+  },
 
-  -- Git related plugins
-  use 'tpope/vim-fugitive'
-  use 'tpope/vim-rhubarb'
-  use 'lewis6991/gitsigns.nvim'
+  { -- Theme inspired by Atom
+    'navarasu/onedark.nvim',
+    config = function()
```
Comment (folke) [inline init.lua:112]: best to add `priority=1000` here. See https://github.com/folke/lazy.nvim#-colorschemes for more info

File: init.lua [hunk 9]
```diff
@@ -1,96 +1,187 @@
...
+    end,
+  },
 
-  -- Add custom plugins to packer from ~/.config/nvim/lua/custom/plugins.lua
-  local has_plugins, plugins = pcall(require, 'custom.plugins')
-  if has_plugins then
-    plugins(use)
-  end
+  -- Fuzzy Finder (files, lsp, etc)
+  { 'nvim-telescope/telescope.nvim', branch = '0.1.x', dependencies = { 'nvim-lua/plenary.nvim' } },
```
Comment (folke) [inline init.lua:153]: `version='*'`

Comment (folke) [reply init.lua:153]: Side note: you can also just specify the name of a dependency, so just `plenary.nvim`. But as I mentioned earlier, since this is a lua dep, you could just skip it altogether.

**Review by folke — COMMENTED** [review]
Looking good! See my other comments

File: .gitignore (hunk 3 above)
Comment (tjdevries) [reply .gitignore:5]: Yeah, I'm just thinking contributors and others will end up adding it on accident constantly haha

File: init.lua (hunk 9 above)
Comment (tjdevries) [reply init.lua:153]: don't I need to put it as a dependency to make sure something installs plenary?

File: README.md (hunk 5 above)
Comment (tjdevries) [reply README.md:51]: yeah, i love this, ty

**Comment by tjdevries** [comment]
Thanks for the review @folke

File: init.lua [hunk 10]
```diff
@@ -82,81 +96,66 @@ require('lazy').setup({
...
-    'folke/which-key.nvim',
-    config = function()
-      vim.o.timeout = true
-      vim.o.timeoutlen = 300
-      require('which-key').setup {}
-    end,
-  },
-
+  -- Useful plugin to show you pending keybinds.
+  { 'folke/which-key.nvim', opt = {} },
```
Comment (folke) [inline init.lua:100]: Should be `opts`. Same for a bunch of others below :)

**Review by folke — COMMENTED** [review]
`opt` -> `opts` :)

File: init.lua (hunk 9 above)
Comment (folke) [reply init.lua]: Just leave it as is. Just wanted to make sure you knew about the auto-loading of lua plugins, but to be fair it wouldn't make a difference here anyway, since `config.defaults.lazy = false`.

So all good!

File: init.lua (hunk 10 above)
Comment (tjdevries) [reply init.lua]: good call haha

File: init.lua (hunk 9 above)
Comment (tjdevries) [reply init.lua]: :+1: awesome, thanks

File: lua/kickstart/plugins/autoformat.lua [hunk 11]
```diff
@@ -0,0 +1,74 @@
+-- autoformat.lua
+--
+-- Use your language server to automatically format your code on save.
+-- Adds additional commands as well to manage the behavior
+
+return {
+  'neovim/nvim-lspconfig',
```
Comment (tjdevries) [inline lua/kickstart/plugins/autoformat.lua:7]: TODO: For myself, could add null-ls here since I know that's a big hang up for a lot of people

Comment (tjdevries) [reply lua/kickstart/plugins/autoformat.lua:7]: meh, i think i'll do this later if I want it

**Comment by varun-balaji** [comment]
In https://github.com/nvim-lua/kickstart.nvim/pull/178/commits/775ff6ac89d6a3fdf812f2fe79855f4a71ec1195, is there a reason to change from `'<c-backspace>'` to `'<M-space>'`? I'm thinking of rebinding it back but I'm not sure if that'll break anything.

**Comment by tjdevries** [comment]
@varun-balaji it won't break anything -- i just think it's a better keybind :)
